# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFG_wEMuUOOfCAsCfljJg90xqOqw66kP
"""

import streamlit as st
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# ================================
# Konfigurasi Halaman
# ================================
st.set_page_config(
    page_title="Deteksi Gambar Real vs Fake",
    layout="wide"
)

st.title("🔍 Deteksi Gambar Real vs Fake (Analisis Gradien)")
st.write("Metode berbasis **Luminance, Gradien, dan Kovarians**")

# ================================
# Fungsi Luminance
# ================================
def rgb_to_luminance(img):
    r, g, b = img[:,:,0], img[:,:,1], img[:,:,2]
    L = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return L.astype(np.float32)

# ================================
# Fungsi Gradien
# ================================
def compute_gradients(L):
    Gx = cv2.Sobel(L, cv2.CV_32F, 1, 0, ksize=3)
    Gy = cv2.Sobel(L, cv2.CV_32F, 0, 1, ksize=3)
    return Gx, Gy

# ================================
# Kovarians Gradien
# ================================
def gradient_covariance(Gx, Gy):
    Gx_flat = Gx.flatten()
    Gy_flat = Gy.flatten()
    M = np.vstack((Gx_flat, Gy_flat)).T
    C = np.cov(M, rowvar=False)
    return C

# ================================
# Rule-Based Klasifikasi
# ================================
def classify_image(C):
    trace = np.trace(C)
    det = np.linalg.det(C)

    # Threshold sederhana (bisa dikalibrasi)
    if trace < 500 and det < 1e6:
        return "FAKE (Kemungkinan AI)", trace, det
    else:
        return "REAL (Kemungkinan Asli)", trace, det

# ================================
# Upload Gambar
# ================================
uploaded_file = st.file_uploader(
    "Upload Gambar",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    img_np = np.array(image)

    # Proses
    L = rgb_to_luminance(img_np)
    Gx, Gy = compute_gradients(L)
    C = gradient_covariance(Gx, Gy)
    result, trace, det = classify_image(C)

    grad_mag = np.sqrt(Gx**2 + Gy**2)

    # ================================
    # Tampilan
    # ================================
    col1, col2, col3 = st.columns(3)

    with col1:
        st.subheader("Gambar Asli")
        st.image(image, use_column_width=True)

    with col2:
        st.subheader("Luminance (Grayscale)")
        st.image(L, clamp=True, use_column_width=True)

    with col3:
        st.subheader("Gradien Magnitude")
        st.image(grad_mag, clamp=True, use_column_width=True)

    # ================================
    # Hasil Analisis
    # ================================
    st.markdown("---")
    st.subheader("📊 Hasil Analisis Statistik")

    st.write("**Covariance Matrix:**")
    st.write(C)

    col4, col5 = st.columns(2)
    with col4:
        st.metric("Trace (Jejak Matriks)", f"{trace:.2f}")
    with col5:
        st.metric("Determinant", f"{det:.2e}")

    st.markdown("### 🧠 Prediksi")
    if "FAKE" in result:
        st.error(result)
    else:
        st.success(result)

    st.info("⚠️ Model ini berbasis **analisis statistik**, bukan deep learning. Cocok untuk riset & baseline deteksi AI image.")

# ================================
# Footer
# ================================
st.markdown("---")
st.caption("Dibangun dengan Streamlit • Analisis Gradien & Kovarians")